name: Dockerize and Push to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ECR_REPOSITORY: health-check

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
        aws-region: us-east-1

    - name: ECR Login
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:latest .

    - name: Tag and Push Docker image to ECR
      run: |
        IMAGE_URI=$(aws ecr describe-repositories --repository-name ${{ env.ECR_REPOSITORY }} --query 'repositories[0].repositoryUri' --output text)

        docker tag ${{ env.ECR_REPOSITORY }}:latest $IMAGE_URI:latest
        docker tag ${{ env.ECR_REPOSITORY }}:latest $IMAGE_URI:${{ github.sha }}

        docker push $IMAGE_URI:latest
        docker push $IMAGE_URI:${{ github.sha }}

        echo "✅ Successfully pushed images:"
        echo "  - $IMAGE_URI:latest"
        echo "  - $IMAGE_URI:${{ github.sha }}"

